name: Container creation

on:
  push:
    branches:
      - 'main'
      - 'ci/test'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    

jobs:
  alpine:
    strategy:
      matrix:
        include:
          - alpine: 3.17
            ruby: '3.1'
          - alpine: 3.17
            ruby: '3.2'
          - alpine: 3.16
            ruby: '2.7'
          - alpine: 3.16
            ruby: '3.0'
          - alpine: 3.16
            ruby: '3.1'
          - alpine: 3.16
            ruby: '3.2'
    runs-on: ubuntu-latest
    name: Create docker alpine images
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build build basic images with alpine ${{ matrix.alpine }} and Ruby ${{ matrix.ruby }}
        uses: docker/build-push-action@v6
        with:
          context: build
          push: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
          target: base
          tags: carstencodes/presentation-build-base:${{ matrix.alpine }}-ruby${{ matrix.ruby }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            RUBY_VERSION=${{ matrix.ruby }}
      - 
        name: Build build pdf images with alpine ${{ matrix.alpine }} and Ruby ${{ matrix.ruby }}
        uses: docker/build-push-action@v6
        with:
          context: build
          push: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
          target: pdf
          tags: carstencodes/presentation-build-pdf:${{ matrix.alpine }}-${{ matrix.ruby }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            RUBY_VERSION=${{ matrix.ruby }}
  debian:
    runs-on: ubuntu-latest
    name: Create docker debian images
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build presentation base images with debian bullseye-slim
        uses: docker/build-push-action@v6
        with:
          context: base
          push: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
          tags: carstencodes/presentation-base:bullseye-slim
