name: Container creation

on:
  push:
    branches:
      - 'main'
      - 'ci/test'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        include:
          - alpine: 3.15
          - alpine: 3.14
    runs-on: ubuntu-latest
    name: Create docker containers
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build presentation base images with alpine ${{ matrix.alpine }}
        uses: docker/build-push-action@v2
        with:
          context: base
          push: true
          tags: carstencodes-presentation-base:${{ matrix.alpine }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
      - 
        name: Build build basic images with alpine ${{ matrix.alpine }}
        uses: docker/build-push-action@v2
        with:
          context: build
          push: true
          target: base
          tags: carstencodes/presentation-build-base:${{ matrix.alpine }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
      - 
        name: Build build pdf images with alpine ${{ matrix.alpine }}
        uses: docker/build-push-action@v2
        with:
          context: build
          push: true
          target: pdf
          tags: carstencodes/presentation-build-pdf:${{ matrix.alpine }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
